### PR TITLE
implement /nar/{store_hash}-{nar_hash}.nar endpoint

### LINKED ISSUE #120: My nix queries /nar/<hash>-<name>.narinfo, not just /<hash>.narinfo
My nix 2.15.1 queries `/nar/<hash>-<name>.narinfo` for some reason, so I had to 

```
location ~ "^/nar/([a-z0-9]{32})-.*\.narinfo$" {
  proxy_pass http://127.0.0.1:5000/$1.narinfo$is_args$args;
  ...
}
```

(It was worth to set it up though, I've seen ~10x speedups in synthetic local tests vs whatever's built into hydra.)

### PR DESCRIPTION
**Pull request by chayleaf**
This should partially fix #120. I've yet to test this.

### CODE REVIEW

**Comment by Mic92** [comment]
Is this now used by default for all queries? Should we adapt our test to also test the new nix version?

**Comment by chayleaf** [comment]
I have no idea, I tried looking in Nix code but couldn't find anything related to it, I just noticed that harmonia wouldn't work for me and this endpoint missing was one of the errors, I don't think this single endpoint would be enough to completely establish new Nix compatibility

**Comment by chayleaf** [comment]
I've found it thanks to the discussion in the linked issue. The problem is that due to previous nix-serve usage Nix cached [this line](https://github.com/edolstra/nix-serve/blob/d6df5bd8584f37e22cff627db2fc4058a4aab5ee/nix-serve.psgi#L31) of narinfo, causing it to query a different URL for as long as the narinfo was still cached. It still isn't clear why `<hash>-<name>.narinfo` was being queried for other users however.

**Comment by Mic92** [comment]
@mergify queue

**Pull request merged**
